# Generated by Django 4.2.16 on 2025-08-15 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku', models.CharField(max_length=54, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('category', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('unit_of_measure', models.CharField(default='EA', max_length=16)),
                ('size', models.CharField(blank=True, max_length=64, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('barcode', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'items',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['sku'], name='items_sku_0a66c0_idx'), models.Index(fields=['barcode'], name='items_barcode_07fc1d_idx'), models.Index(fields=['category'], name='items_categor_694f25_idx')],
            },
        ),
    ]
