# Generated by Django 4.2.16 on 2025-08-17 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('INBOUND', '입고'), ('OUTBOUND', '출고'), ('ADJUSTMENT', '조정')], max_length=20)),
                ('quantity_change', models.IntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('inventory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_logs', to='inventory.inventory')),
            ],
            options={
                'db_table': 'inventory_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
